# Generated by Django 6.1.1 on 2026-09-23 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='in_response_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='experience',
            name='phenomena',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='experiences.phenomenon'),
        ),
        migrations.AddField(
            model_name='experience',
            name='practice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='experiences.practice'),
        ),
        migrations.AddField(
            model_name='resonance',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances', to='experiences.experience'),
        ),
        migrations.AddField(
            model_name='resonance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='resonance',
            constraint=models.UniqueConstraint(fields=('member', 'experience'), name='one_resonance_each'),
        ),
    ]
