# Generated by Django 6.1.1 on 2026-09-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone, including search engines'), ('community', 'Only Mettakin members')], max_length=20),
        ),
    ]
