"""Draws Mettakin's pixel icons from ASCII art into templates/_icons.html.

Edit an icon below, then run: python design/icons.py
"""

from pathlib import Path

ICONS = {
    "lotus": """
.....#.....
....###....
.#..###..#.
.##.###.##.
.###.#.###.
..#######..
...#####...
#.........#
.#########.
""",
    "pencil": """
.........##
........###
.......###.
......###..
.....###...
....###....
...###.....
..###......
.##........
###........
##.........
""",
    "heart": """
.##...##.
####.####
#########
#########
.#######.
..#####..
...###...
....#....
""",
    "chat": """
#########
#.......#
#.#.#.#.#
#.......#
#########
..##.....
.#.......
""",
    "bulb": """
..#####..
.#.....#.
#.......#
#...#...#
#...#...#
.#.....#.
..#...#..
..#####..
..#####..
...###...
""",
    "user": """
...###...
..#####..
..#####..
...###...
.........
.#######.
#########
#########
""",
    "enter": """
.....#####
.....#...#
..#..#...#
...#.#...#
#######..#
...#.#...#
..#..#...#
.....#...#
.....#####
""",
    "help": """
..####..
.#....#.
......#.
.....#..
....#...
....#...
........
....#...
""",
    "lock": """
..###..
.#...#.
.#...#.
#######
###.###
###.###
#######
""",
    "spark": """
....#....
....#....
..#.#.#..
...###...
#########
...###...
..#.#.#..
....#....
....#....
""",
    "up": """
....#....
...###...
..#####..
.#######.
....#....
....#....
....#....
""",
    "back": """
...#.....
..#......
.########
..#......
...#.....
""",
}


def path(art):
    rows = art.strip("\n").splitlines()
    parts = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            if row[x] == "#":
                start = x
                while x < len(row) and row[x] == "#":
                    x += 1
                parts.append(f"M{start} {y}h{x - start}v1h{start - x}z")
            else:
                x += 1
    return "".join(parts), max(len(r) for r in rows), len(rows)


def main():
    symbols = []
    for name, art in ICONS.items():
        d, width, height = path(art)
        symbols.append(
            f'<symbol id="i-{name}" viewBox="0 0 {width} {height}"><path d="{d}"/></symbol>'
        )
    svg = '<svg class="sprite" aria-hidden="true">' + "".join(symbols) + "</svg>\n"
    target = Path(__file__).resolve().parent.parent / "templates" / "_icons.html"
    target.write_text("{# Generated by design/icons.py. Edit the ASCII art there. #}\n" + svg)


if __name__ == "__main__":
    main()
